sudo: false

language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

addons:
  apt:
    packages:
      - socat

cache:
  apt: true

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -race ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.6" && cd narada && goveralls -service=travis-ci
